name: Main

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Create zip
        run: make release
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: '*.zip'
